### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GuangtaoLyu** [YilanDong19/Machine-learning-with-ABIDE#1]
Traceback (most recent call last):
  File "/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D' -> '/home/xxx/PycharmProjects/xxx/Data_download_prepare/data/ABIDE_pcp/cpac/filt_noglobal/50003/Arois_aal.1D'

I clone your code, and add path in the fetch_data.py and ABIDEParser.py.  '/home/xxx/PycharmProjects/xxx/Data_download_prepare'

**Comment by YilanDong19** [comment]
I guess you probably changed other places. After you download the code, please only change 'root_folder' in the fetch_data.py and ABIDEParser.py, like root_folder = 'D:\\test', the 50003 subject will be downloaded into 'D:\test\ABIDE_pcp\cpac\filt_noglobal\50003\Pitt_0050003_rois_aal.1D'.
I noticed that you may not use this code in windows system, you can try it in windows first by only changing the 'root_folder', once you succeed, then you can move everything to linux system with more changes.

**Comment by YilanDong19** [comment]
> Traceback (most recent call last): File "/lib/python3.7/shutil.py", line 566, in move os.rename(src, real_dst) FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D' -> '/home/xxx/PycharmProjects/xxx/Data_download_prepare/data/ABIDE_pcp/cpac/filt_noglobal/50003/Arois_aal.1D'
> 
> I clone your code, and add path in the fetch_data.py and ABIDEParser.py. '/home/xxx/PycharmProjects/xxx/Data_download_prepare'

I guess you probably changed other places. After you download the code, please only change 'root_folder' in the fetch_data.py and ABIDEParser.py, like root_folder = 'D:\test', the 50003 subject will be downloaded into 'D:\test\ABIDE_pcp\cpac\filt_noglobal\50003\Pitt_0050003_rois_aal.1D'.
I noticed that you may not use this code in windows system, you can try it in windows first by only changing the 'root_folder', once you succeed, then you can move everything to linux system with more changes.

**Comment by GuangtaoLyu** [comment]
thanks . i also changed \\ with /.
i will try it on windows.



---Original---
From: "Yilan ***@***.***&gt;
Date: Thu, Mar 3, 2022 15:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YilanDong19/Machine-learning-with-ABIDE] error (Issue #1)




  
Traceback (most recent call last): File "/lib/python3.7/shutil.py", line 566, in move os.rename(src, real_dst) FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D' -&gt; '/home/xxx/PycharmProjects/xxx/Data_download_prepare/data/ABIDE_pcp/cpac/filt_noglobal/50003/Arois_aal.1D'
 
I clone your code, and add path in the fetch_data.py and ABIDEParser.py. '/home/xxx/PycharmProjects/xxx/Data_download_prepare'
  
I guess you probably changed other places. After you download the code, please only change 'root_folder' in the fetch_data.py and ABIDEParser.py, like root_folder = 'D:\test', the 50003 subject will be downloaded into 'D:\test\ABIDE_pcp\cpac\filt_noglobal\50003\Pitt_0050003_rois_aal.1D'.
 I noticed that you may not use this code in windows system, you can try it in windows first by only changing the 'root_folder', once you succeed, then you can move everything to linux system with more changes.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvguangtao** [comment]
there still are the same error.
and 50003 is empty.
![image](https://user-images.githubusercontent.com/57834464/156584937-5c7b8e36-edfe-427a-b9ba-5c9a6681015b.png)

**Comment by lvguangtao** [comment]
still error. and 50003 is empty.
![image](https://user-images.githubusercontent.com/57834464/156585239-ee791e4e-8877-4cc5-ad6f-8f23bf4b8b19.png)

**Comment by GuangtaoLyu** [comment]
![image](https://user-images.githubusercontent.com/57834464/156585435-0baca3fb-3f44-4506-9fb6-e24ae99ecff4.png)

still error.
and the 50003 is empty.

**Comment by YilanDong19** [comment]
> ![image](https://user-images.githubusercontent.com/57834464/156585435-0baca3fb-3f44-4506-9fb6-e24ae99ecff4.png)
> 
> still error. and the 50003 is empty.

I downloaded this code, and only changed root_folder in the fetch_data.py and ABIDEParser.py. It worked
root_folder = 'D:\\test'
![image](https://user-images.githubusercontent.com/56785684/156595027-b975f4da-59f7-4c31-89c0-7fb67dc11193.png)

**Comment by GuangtaoLyu** [comment]
thank you . i will try it again .



---Original---
From: "Yilan ***@***.***&gt;
Date: Thu, Mar 3, 2022 23:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YilanDong19/Machine-learning-with-ABIDE] error (Issue #1)




  

 
still error. and the 50003 is empty.
  
I downloaded this code, and only changed root_folder in the fetch_data.py and ABIDEParser.py. It worked
 root_folder = 'D:\test'
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GuangtaoLyu** [comment]
> > ![image](https://user-images.githubusercontent.com/57834464/156585435-0baca3fb-3f44-4506-9fb6-e24ae99ecff4.png)
> > still error. and the 50003 is empty.
> 
> I downloaded this code, and only changed root_folder in the fetch_data.py and ABIDEParser.py. It worked root_folder = 'D:\test' ![image](https://user-images.githubusercontent.com/56785684/156595027-b975f4da-59f7-4c31-89c0-7fb67dc11193.png)

still error.
i only change the root_path. 'D:\\test'
this may be the abide datasets not be download correctly?
if i  run datasets.fetch_abide_pcp successfully, the ****.1d should be downloaded?

**Comment by YilanDong19** [comment]
> > > ![image](https://user-images.githubusercontent.com/57834464/156585435-0baca3fb-3f44-4506-9fb6-e24ae99ecff4.png)
> > > still error. and the 50003 is empty.
> > 
> > 
> > I downloaded this code, and only changed root_folder in the fetch_data.py and ABIDEParser.py. It worked root_folder = 'D:\test' ![image](https://user-images.githubusercontent.com/56785684/156595027-b975f4da-59f7-4c31-89c0-7fb67dc11193.png)
> 
> still error. i only change the root_path. 'D:\test' this may be the abide datasets not be download correctly? if i run datasets.fetch_abide_pcp successfully, the ****.1d should be downloaded?

Yes, if it run successfully, the ****.1d will be downloaded. If you only change the root_folder but still have an error, it may be caused by differences in python package versions.
I uploaded the requirements.txt in each project, please check. datasets.fetch_abide_pcp is part of nilearn. I am using nilearn==0.6.2
