### ISSUE TITLE
Same error with `FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D'`

### ISSUE THREAD

**Issue by zwencccca** [YilanDong19/Machine-learning-with-ABIDE#2]
OS: MacOS Monterey
Environment: Anaconda + Pycharm + python3.8
Library version: `nilearn` 0.9.0, `numpy` 1.19.2, others two are the same
I can't install the specified version on the Anaconda environment, I hope this won't be the error reason.

The Error goes:
`Traceback (most recent call last):
  File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D' -> /Mypath/Machine-learning-with-ABIDE/Data_download_prepare/ABIDE_pcp/cpac/filt_noglobal/50003/Arois_aal.1D'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/Machine-learning-with-ABIDE/Data_download_prepare/fetch_data.py", line 52, in <module>
    shutil.move(base + filemapping[fl], subject_folder)
  File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D'`

**Purposed Solution**
Whether you could upload the downloaded file to your repo?

**Comment by YilanDong19** [comment]
> OS: MacOS Monterey Environment: Anaconda + Pycharm + python3.8 Library version: `nilearn` 0.9.0, `numpy` 1.19.2, others two are the same I can't install the specified version on the Anaconda environment, I hope this won't be the error reason.
> 
> The Error goes: `Traceback (most recent call last): File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 791, in move os.rename(src, real_dst) FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D' -> /Mypath/Machine-learning-with-ABIDE/Data_download_prepare/ABIDE_pcp/cpac/filt_noglobal/50003/Arois_aal.1D'`
> 
> `During handling of the above exception, another exception occurred:`
> 
> `Traceback (most recent call last): File "/Machine-learning-with-ABIDE/Data_download_prepare/fetch_data.py", line 52, in <module> shutil.move(base + filemapping[fl], subject_folder) File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 811, in move copy_function(src, real_dst) File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 435, in copy2 copyfile(src, dst, follow_symlinks=follow_symlinks) File "/Mypath/.conda/envs/Data_download_prepare/lib/python3.8/shutil.py", line 264, in copyfile with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst: FileNotFoundError: [Errno 2] No such file or directory: 'N/Arois_aal.1D'`
> 
> **Purposed Solution** Whether you could upload the downloaded file to your repo?

Thanks for your interest. Unfortunately, I don't think I'm allowed to upload ABIDE's database even though it's public. Another reason I insist on using nilearn to download data is to prove that my experiment is reliable.

For your error, I think this is caused by nilearn version. Mine is `nilearn` 0.6.2, while you are using `nilearn` 0.9.0. In the Data_download_prepare/requirements.txt file, it says that:
nilearn==0.6.2
numpy==1.18.2
scikit_learn==1.0.2
scipy==1.4.1

Hope you can find this useful.
